[package]
name = "school_notes_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
candle = "0.1.0"
candle-core = "0.11.0"
candle-nn = "0.11.0"
candle-transformers = "0.11.0"
clap = "4.6.6"
docx-rs = "0.4.22"
hf-hub = "0.4"
pdf-extract = "0.12.0"
pptx = "0.1.0"
pptx-to-md = "1.0.0"
rusqlite = "0.40.2"
serde_json = "1.0.151"
tokenizers = "0.23.2"
walkdir = "2.5.0"
